# Generated by Django 2.2 on 2019-05-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190513_0217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
