# Generated by Django 2.2 on 2019-05-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='no title', max_length=100),
            preserve_default=False,
        ),
    ]
